apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stub-ingress
spec:
  rules:
    - host: example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stub
                port:
                  number: 80
