apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-demo
  labels:
    {{- include "demo-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: demo
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: demo
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: demo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
