name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run shellcheck
        run: |
          sudo apt-get update -y
          sudo apt-get install -y shellcheck
          shellcheck $(git ls-files '*.sh')

  yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run yamllint
        run: |
          sudo pip install yamllint
          yamllint $(git ls-files '*.yaml' '*.yml')

  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ruff check
        run: |
          pip install ruff
          ruff check $(git ls-files '*.py')

  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Run terraform fmt -check
        run: terraform fmt -check -recursive $(git ls-files '*.tf')
